version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_WEBSOCKET_URL=ws://localhost:5000
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MAX_GAMES_PER_SERVER=100
      - HEALTH_CHECK_INTERVAL=30000
      - SERVER_REGION=dev
      - SERVER_ID=dev-1
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
    restart: unless-stopped
